### ISSUE TITLE
Multiple Commands Build Error

### ISSUE THREAD

**Issue by KaranShah95** [googlecodelabs/tensorflow-for-poets-2#107]
Showing Recent Messages
:-1: Multiple commands produce '/Users/karanshah/Library/Developer/Xcode/DerivedData/tflite_photos_example-hdnywmlpwpmthuekrlxjakvnxhzq/Build/Products/Debug-iphonesimulator/tflite_photos_example.app/Info.plist':
1) Target 'tflite_photos_example' (project 'tflite_photos_example') has copy command from '/Users/karanshah/tensorflow-for-poets-2/ios/tflite/Info.plist' to '/Users/karanshah/Library/Developer/Xcode/DerivedData/tflite_photos_example-hdnywmlpwpmthuekrlxjakvnxhzq/Build/Products/Debug-iphonesimulator/tflite_photos_example.app/Info.plist'
2) Target 'tflite_photos_example' (project 'tflite_photos_example') has process command with output '/Users/karanshah/Library/Developer/Xcode/DerivedData/tflite_photos_example-hdnywmlpwpmthuekrlxjakvnxhzq/Build/Products/Debug-iphonesimulator/tflite_photos_example.app/Info.plist'

<img width="1440" alt="screenshot 2019-01-02 at 11 28 50 pm" src="https://user-images.githubusercontent.com/38445579/50627100-c01e7800-0ee6-11e9-85a8-a2d0507496c2.png">

**Comment by iDuckDark** [comment]
Xcode Workspace settings > Change to Legacy Build System, it worked for me after that

**Comment by ml-illustrated** [comment]
Instruction by @iDuckDark seems to have done the trick. Here's some more background [from Apple](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10):

File > Workspace/Project Settings > Build System > Legacy Build System

**Comment by KaranShah95** [comment]
@iDuckDark and @ml-illustrated you guys are correct. It worked for me thanks.
