### ISSUE TITLE
StylizeActivity missing

### ISSUE THREAD

**Issue by freeknortier** [googlecodelabs/tensorflow-for-poets-2#111]
https://github.com/googlecodelabs/tensorflow-for-poets-2/tree/master/android/tfmobile

This repo does not contain the stylize demo although it claims to.

**Comment by freeknortier** [comment]
@MarkDaoust please look at this.

**Comment by MarkDaoust** [comment]
Thanks for reporting the problem

I've fixed the Readme. 

https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/android/tfmobile/README.md
