### ISSUE TITLE
Gradle 'android' project refresh failed.

### ISSUE THREAD

**Issue by renschler** [googlecodelabs/tensorflow-for-poets-2#5]
I'm running the most recent stable release of Android Studio 2.3.3 and I get the following error:
<img width="1164" alt="screen shot 2017-09-15 at 12 07 44 am" src="https://user-images.githubusercontent.com/3973468/30467410-f529e218-99a9-11e7-9b57-9b031aa53945.png">

I downloaded Android Studio 3.0 Beta 2, to see if that would fix things, and this time got a different gradle error saying that the minimum supported Gradle version is 4.0-rc-1.

As someone who is totally new to android dev, walking through this codelab, I'm not sure what to do.

**Comment by renschler** [comment]
*Update*:
In the android folder, i edited the build.gradle file so that under dependencies the classpath was "com.android.tools.build:gradle:2.3.3" instead of 3.0.0-beta2

The grade build finished this time using the stable version of android studio.

**Comment by ojtramp** [comment]
An alternative solution is to add repositories to the build.gradle file (thanks to Gabriele Mariotti [here](https://stackoverflow.com/questions/45874344/android-gradle-plugin-error-in-android-studio-3-0-beta-3))

**Option One** - add maven repository

```
buildscript {
    //..
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    //..
}
```
**Option Two** - Google repository if you are using Android Studio 3.x and gradle v.4 (this didn't work for me as I was using v2.3.3 on MacOSX)
```
buildscript {
    repositories {
        ...
        // You need to add the following repository to download the
        // new plugin.
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta-2'
    }
}
```

**Comment by Sagarsharma4244** [comment]
I'm using **ubuntu16.04** 
--------------------------------------------
friday@friday-HP-Notebook:/etc$ gradle -v
**Gradle 3.0**
but still getting  this

**Error:Cause: https://downloads.gradle.org/distributions/gradle-3.0.0-all.zip**

**Comment by Sagarsharma4244** [comment]
I just downloaded the repository again and it just worked. Maybe it was my fault or a new commit.But If you are having the same issue just try to download the repository again and try to sync it. 😄 💯

**Comment by japer21** [comment]
Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: 

I have this classpath : classpath 'com.android.tools.build:gradle:3.1.2'

And  I am trying to implement the android tflite demo but on my model.

**Comment by Atajan1993** [comment]
I don't know

**Comment by renschler** [comment]
Closing bc stale.
