### ISSUE TITLE
Toco not working for Tensorflow 1.9

### ISSUE THREAD

**Issue by PoojaB26** [googlecodelabs/tensorflow-for-poets-2#68]
Ubuntu : 16.0.4
Tensorflow : 1.9

I was trying the last step in this codelab ->
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/index.html#2

`toco \
  --input_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/optimized_graph.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 \
  --input_array=input \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT`

And this would throw an error: `--graph_def_file, --saved_model_dir is required.`

Read another issue where TOCO doesnt work for 1.8, I guess the issue is still not resolved for 1.9
Works fine with 1.7 though.

**Comment by dhairy1234** [comment]
Same here if changed --input_files to --graph_def_files then it just shows error:

**Comment by tigrandev** [comment]
Try this one
toco \
  --graph_def_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/optimized_graph.lite \
  --output_format=TFLITE \
  --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 \
  --input_array=input \
  --output_array=final_result \
  --inference_type=FLOAT \
  --inference_input_type=FLOAT

**Comment by Sagarsharma4244** [comment]
It works for me @tigrandev 
Actually, for Tensorflow 1.9 you are supposed to change the `--input_file` to `graph_def_file` and not include the `--input_format=TENSORFLOW_GRAPHDEF`
But It is not updated in the  [Codelabs's TFLite Tutorial ](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/index.html?index=..%2F..%2Findex#2)

**Comment by Sagarsharma4244** [comment]
@PoojaB26 You can close the Issue if you want.

**Comment by PoojaB26** [comment]
@Sagarsharma4244 I'll try it out, thanks.

**Comment by abumubaarak** [comment]
@tigrandev what is the value  of input_shape
